services:
  - type: web
    name: faculty-attendance
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn faculty_attendance.wsgi:application --bind 0.0.0.0:8000"
    plan: free
    branch: main
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: faculty_attendance.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
