# Generated by Django 5.2.1 on 2025-05-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="facultyprofile",
            name="personal_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
